# Generated by Django 4.1.13 on 2024-12-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='address',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
