# Generated by Django 4.1.13 on 2024-12-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pupil_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='id_number',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='pupil',
            name='number',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='pupil',
            name='parent',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
