# Generated by Django 4.1.13 on 2024-12-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pupil_id_number_pupil_number_pupil_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pupil',
            old_name='number',
            new_name='cell_number',
        ),
    ]
